workflows:
  ionic-ios-debug-manual:
    name: iOS Debug (Manual Signing)
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies & Build web
        script: |
          npm install
          npm run build
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Set up Manual Signing
        script: |
          # Prepares the keychain with files you uploaded to Codemagic UI
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --configuration Debug

    artifacts:
      - build/ios/ipa/*.ipa